cursor #e1e2e9
cursor_text_color #c3c6cf

foreground            #e1e2e9
background            #111318
selection_foreground  #263141
selection_background  #bcc7dc
url_color             #a5c8fe

color0   #111318
color1   #ff729b
color2   #7ffe91
color3   #fff872
color4   #8bb3f1
color5   #2a4775
color6   #a5c8fe
color7   #eff5ff
color8   #989da5
color9   #ff9fba
color10  #a5ffb2
color11  #fffaa5
color12  #b3d0ff
color13  #c0d9ff
color14  #d6e6ff
color15  #f8fbff
